# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: root
  web:
    #image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    stdin_open: true
    tty: true